### ISSUE TITLE
Missing information with property pointing

### ISSUE THREAD

**Issue by JensMueller2709** [StuPro-TOSCAna/TOSCAna#509]
The Cloud Foundry plugin needs to know from where a value of input comes from if a variable points to a property.
We need to know it to detect the semantic of the input variable. Then we are able to set the environment variable with the right value.

Since it is difficult to explain here a small example with our Lamp-noinput template.
The sections which are important in this context:
```yml
topology_template:
  node_templates:
  my_app:
  ...
      inputs:
          database_host: { get_attribute: [ server, private_address ] }
          database_user: { get_property: [ my_db,  user ] }
          database_password: { get_property: [ my_db, password ] }
          database_name: { get_property: [ my_db, name ] }
          database_port: { get_property: [ my_db, port ] }
```
and
```yml
my_db:
      type: tosca.nodes.Database.MySQL
      properties:
        name: mydb
        user: root
        password: abc
        port: 3306
```

At the moment the model sets automatically the values of the my_db to the input variables. So we get for `database_user`the value `root`. We have no possibility to get the information that this value comes from the name property of my_db. 

We need the information that the variable `database_user` points to the property `user` of my_db.
If you have further questions, just ask.
