### ISSUE TITLE
Allow upload of large files

### ISSUE THREAD

**Issue by c-mueller** [StuPro-TOSCAna/TOSCAna#73]
Currently the Upload size is limited to 10 MB because that is set as default by the Spring Framework. 
You might think the problem is simple to solve, by just increasing the limits in the properties Like this:
```YAML
http:
  multipart:
    enabled: true
    max-file-size: 1000MB
    max-request-size: 10000MB:
```

However if you modify the properties the core application simply refuses to start (it's hanging).

We need to find a solution to fix this issue. 
Using Tomcats ServletFileUpload was one idea however this does not work in any environment except for Insomnia making it useless.

**Comment by orferch** [comment]
Maybe I found the Fix?

Changed it from
```YAML
spring:
  main:
    banner-mode: "off"
  http:
  	multipart:
     enabled: true
     max-file-size: 10000MB
     max-request-size: 100000MB:
  ```
to
```YAML
spring:
    main:
        banner-mode: "off"
    http:
        multipart:
            enabled: true
            max-file-size: 1000MB
            max-request-size: 1000MB
```

and could upload a 40 MB CSAR
